### ISSUE TITLE
Java usage documentation

### ISSUE THREAD

**Issue by rubixhacker** [Commit451/ehhttp#1]
Please add documentation for how to call this from Java, otherwise an implemententer would need to understand how Kotlin extension functions are compiled to Java bytecode. 

For example

`val observable = call.toObservable()`

would be

`Observable<?> observable = Callkt.toObservable(call)`

**Comment by Jawnnypoo** [comment]
Ahh thanks. Added some docs, changed the name so it would make more sense. 👍
