### ISSUE TITLE
Multiple subscribers will cause  crash

### ISSUE THREAD

**Issue by digitalbuddha** [Commit451/ehhttp#2]
https://github.com/Commit451/ehhttp/blob/35d913e6f3c6d2604ae8c08428c79b608ae04d55/src/main/kotlin/com/commit451/ehhttp/CallObservable.kt#L20

I believe you need to clone a call prior to executing since you can have multiple subscribers to same CallObservable.

**Comment by Jawnnypoo** [comment]
I see, I did note that calls were being cloned in Retrofit, but the problem that I saw was that if you were to call `cancel` on a call, I don't think it would cancel the cloned call, do you know if this is the case?

**Comment by Jawnnypoo** [comment]
Thanks, fixed in `1.2.0`
